name: flutter_nord_theme
description: Flutter theme using the Nord color palette.
version: 0.0.1
author: Firefnix
repository: https://github.com/Firefnix/flutter-nord-theme

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
