name: flutter_nord_theme
description: Flutter theme using the Nord color palette.
version: 2.0.1
repository: https://github.com/Firefnix/flutter-nord-theme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
