name: flutter_nord_theme
description: An arctic, north-bluish theme for Flutter, based on the Nord theme.
version: 2.1.0
repository: https://github.com/Firefnix/flutter-nord-theme

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
